# Generated by Django 4.2.28 on 2026-02-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_dailytracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiongoal',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
