# Generated by Django 4.2.28 on 2026-02-27 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0003_nutritiongoal_age_nutritiongoal_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiongoal',
            name='last_model_trained',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='maintenance_calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories', models.FloatField()),
                ('weight', models.FloatField()),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('workout_minutes', models.IntegerField(blank=True, null=True)),
                ('protein_grams', models.FloatField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
