# Generated by Django 4.2.28 on 2026-03-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_nutritiongoal_last_model_trained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiongoal',
            name='primary_goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('recomposition', 'Body Recomposition')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
