# Generated by Django 4.2.28 on 2026-03-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_nutritiongoal_primary_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytracking',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
