# Generated by Django 4.2.28 on 2026-03-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_dailytracking_weight_kg'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cravingentry',
            index=models.Index(fields=['user', '-logged_at'], name='goals_cravi_user_id_a2c9ed_idx'),
        ),
    ]
