# Generated by Django 4.2.28 on 2026-03-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_cravingentry_goals_cravi_user_id_a2c9ed_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytracking',
            name='mood',
            field=models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('low', 'Low')], max_length=10, null=True),
        ),
    ]
