# Generated by Django 4.2.28 on 2026-03-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_dailytracking_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytracking',
            name='cheat_calories_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='daily_cheat_allowance',
            field=models.IntegerField(default=0),
        ),
    ]
