# Generated by Django 4.2.28 on 2026-03-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foodentry',
            index=models.Index(fields=['user', '-logged_at'], name='food_fooden_user_id_a88eac_idx'),
        ),
        migrations.AddIndex(
            model_name='foodentry',
            index=models.Index(fields=['user', 'meal_type'], name='food_fooden_user_id_460897_idx'),
        ),
    ]
