# Generated by Django 4.2.28 on 2026-04-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodentry_food_fooden_user_id_a88eac_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foodentry',
            index=models.Index(fields=['name'], name='food_fooden_name_0b8538_idx'),
        ),
        migrations.AddIndex(
            model_name='foodentry',
            index=models.Index(fields=['calories'], name='food_fooden_calorie_057aad_idx'),
        ),
    ]
