# Generated by Django 4.2.28 on 2026-02-24 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('benefits', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('evidence_level', models.CharField(choices=[('strong', 'Strong'), ('moderate', 'Moderate'), ('limited', 'Limited')], default='limited', max_length=20)),
                ('interactions', models.JSONField(default=list, help_text='Drug interactions')),
                ('image', models.ImageField(blank=True, null=True, upload_to='supplement_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='supplements.supplement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('supplement', 'user')},
            },
        ),
    ]
